### PR TITLE
Add zazu app to electron apps.

### PR DESCRIPTION
**Pull request by blainesch**
Thanks for looking! [:

### CODE REVIEW

**Comment by blainesch** [comment]
I updated to the [original](https://www.iconfinder.com/icons/51188/feather_photoshop_icon). I hope it's good enough. [:

**Comment by kevinsawicki** [comment]
@blainesch do you have something 256x256?

**Comment by blainesch** [comment]
Nope ]: I'll contact the author.

**Comment by blainesch** [comment]
Pretty logo [:

**Comment by blainesch** [comment]
@kevinsawicki I got the updated logo now.

**Pull request merged**
