### PR TITLE
Added the Fudget, the popular budgeting app. Original iOS version was…

### PR DESCRIPTION
**Pull request by fruitangdan**
… created using Cordova and has received over 300,000 downloads. Android version was later released. Now here is the Mac version, creating by adapting the original codebase and wrapping in Electron. Thank you Electron team for creating such a great framework!

### CODE REVIEW

**Comment by zeke** [comment]
Thanks, @fruitangdan 

I'm not able to access https://bitbucket.org/fruitangdan/fudget -- is it a private repo?

**Comment by fruitangdan** [comment]
Hi Zeke,

Thanks for your message. 

Yes. It is private. Should we remove it from the yml file?

Cheers,

Danny

**Comment by zeke** [comment]
> Should we remove it from the yml file?

Yeah

**Comment by fruitangdan** [comment]
Thanks. I've removed the repository field.

**Pull request merged**
