### PR TITLE
create contributing.md

### PR DESCRIPTION
**Pull request by zeke**
This PR adds a `contributing.md` file explaining the various ways to add an app, and some submission guidelines derived from @sindresorhus' [awesome-electron](https://github.com/sindresorhus/awesome-electron) repo.

### CODE REVIEW

**Comment by zeke** [comment]
cc @kevinsawicki @groundwater @Haacked

**Comment by zeke** [comment]
The build is failing because Travis's `nvm` installer is not working...

**Comment by zeke** [comment]
..and it's passing.

**Comment by groundwater** [comment]
I've been thinking, if we're going to split up apps per directory, what if we go a step further and give apps their own pages? We could auto-generate these from the `.yaml` file or just let folks post READMEs

I'm thinking this would feel like a primordial app store.

It would be cool to also display:

- [ ] icon & description
- [ ] license type / cost
- [ ] category
- [ ] keywords
- [ ] screenshots
- [ ] link to download

We would probably want a common warning that we do not officially endorse or support any apps listed.

**Comment by zeke** [comment]
Gonna go ahead and ship this as-is, but really love the ideas above, @groundwater.

**Comment by groundwater** [comment]
@zeke yah, it was off topic - where is a good spot for the issue?

**Pull request merged**
