### PR TITLE
Add Nuclear music player

### PR DESCRIPTION
**Pull request by nukeop**

### CODE REVIEW

**Comment by zeke** [comment]
> STREAMING FOR NOTHING, MUSIC FOR FREE

Dire Straits reference? :)

**Comment by nukeop** [comment]
> Dire Straits reference? :)

That's right ;)

**Comment by zeke** [comment]
You look uncannily similar to Slavoj Zizek. Probably spelled that wrong.

**Comment by nukeop** [comment]
Yeah I get that a lot

**Pull request merged**
