### PR TITLE
Added Joplin

### PR DESCRIPTION
**Pull request by laurent22**
This is for [Joplin](https://github.com/laurent22/joplin), a note-taking and to-do application.

Here are the URLs and screenshots:

- Website: http://joplin.cozic.net/

- Main image:

- Secondary image:

### CODE REVIEW

**Comment by zeke** [comment]
CI is failing because the icon file is misnamed:

```
 1) human-submitted app data joplin icon exists as joplin-icon.png:
      joplin-icon.png not found
```

**Comment by laurent22** [comment]
Ok this is done

**Comment by laurent22** [comment]
Hello, is there something I need to do to get the app approved?

**Comment by codebytere** [comment]
@laurent22 looks like the build is still failing on a parse error.

**Pull request merged**
