### PR TITLE
Adding paintsupreme3d

### PR DESCRIPTION
**Pull request by markusmoenig**

### CODE REVIEW

**Comment by tborychowski** [comment]
I would guess that the name ([similarly to the `package.json`](https://docs.npmjs.com/files/package.json#name)) should be a standardised identifier (so no spaces).

**Comment by tborychowski** [comment]
seems that there might be an error with one of your keywords: https://travis-ci.org/electron/electron-apps/jobs/262953671#L521

**Comment by markusmoenig** [comment]
Hi

It seems to say that the category should be one of a specified list of 26 valid categories.

Where can I find that list so that I can pick a valid category ?

Thanks

-Markus

--
Markus Mönig
markus@moenig.tv <mailto:markus@moenig.tv>

**Comment by tborychowski** [comment]
have you looked into the https://github.com/electron/electron-apps/blob/master/contributing.md#adding-your-app-by-hand- ? :-)

**Comment by markusmoenig** [comment]
Sorry, seem to have overlooked that one ;) Retrying with a valid category.

-Markus

--
Markus Mönig
markus@moenig.tv <mailto:markus@moenig.tv>

**Comment by zeke** [comment]
👍 

Thanks for helping out, @tborychowski

**Pull request merged**
