### PR TITLE
Add Shopify to apps list

### PR DESCRIPTION
**Pull request by feens**

### CODE REVIEW

**Comment by zeke** [comment]
Hi @feens. Does Shopify have a desktop app? I don't see a link to it on the homepage.

**Comment by feens** [comment]
We do in the Mac App Store currently, Windows App Store is pending.  We haven't linked to it/them from our website yet.

**Comment by zeke** [comment]
Got it. In that case can you link to the MAS website URL?

**Comment by zeke** [comment]
(You can update the entry here when downloads are available for other platforms)

**Comment by feens** [comment]
@zeke made that change

**Comment by zeke** [comment]
👍

**Pull request merged**
