### PR TITLE
add Iperius Console

### PR DESCRIPTION
**Pull request by matteoannibali**

### CODE REVIEW

**Comment by zeke** [comment]
🔮 _Iperius Console_ ✨ sounds like a spell if I've ever heard one.

**Comment by matteoannibali** [comment]
image

**Comment by vanessayuenn** [comment]
Hi @matteoannibali, not sure if that was a mistake, but the still image you uploaded does not show that the app is built with electron. Please check out [these prior PRs](https://github.com/electron/electron-apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) for reference as to what can work as proofs. Thanks!

**Comment by matteoannibali** [comment]
image

**Pull request merged**
