### PR TITLE
fix README.md MIT Link

### PR DESCRIPTION
**Pull request by kstar0714**

### CODE REVIEW

**Comment by zeke** [comment]
I wonder if this repo should share a license with electron/electron, or have its own... 🤔 

Paging @lee-dohm.

**Comment by lee-dohm** [comment]
@zeke Since this repo contains scripts and such too, you could probably go either way because you'll probably be using MIT here as well. Generally though since the initial copyright years are going to be different, I would lean toward having a separate `LICENSE` here.

**Comment by zeke** [comment]
> I would lean toward having a separate LICENSE here.

I agree. @kstar0714 would be willing to add that?

**Comment by kstar0714** [comment]
I`ll try.

**Comment by zeke** [comment]
@kstar0714 I'm gonna close this but feel free to respond here if you want to pick this effort up again. Thanks.

**Pull request closed without merging**
