### PR TITLE
add fangyuanjian

### PR DESCRIPTION
**Pull request by yanue**

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the submission, @yanue. We would be happy to include this app on the website, but first I have a request.

Because this is the first non-English app that's been submitted, I would like to suggest adding a `locales` property to the YML file to denote that this app is only available in Chinese. The `electron/electron` docs have translations in both `zh-CN` and `zh-TW`. Which of those make sense for "fangyuanjian"?

I'm thinking maybe something like this:

```yml
name: fangyuanjian
description: '办公即时通讯,自由办公,组织架构'
website: 'http://bzsns.cn/'
keywords:
  - "即时通讯"
  - "组织架构"
  - "场地服务"
  - "自由办公"
  - "组织架构"
locales:
  - "zh-CN"
```

cc @zcbenz and @Stone-Jay, @ArisLittle, and @sqrthree who have all helped out translating Electron's docs to Chinese.

**Comment by Stone-Jay** [comment]
```
locales:
  - "zh-CN"
```

**Comment by ArisLittle** [comment]
For example, the string in description key:
'办公即时通讯,自由办公,组织架构' - This is `zh-CN`
'辦公即時通訊,自由辦公,組織架構' - This is `zh-TW`
so the `zh-CN` makes sense

**Comment by yanue** [comment]
@zeke i have added a locales line, additionally i also can translate it into English.

**Comment by zeke** [comment]
> additionally i also can translate it into English.

That would be great! How about something like this:

```yml
description: "办公即时通讯,自由办公,组织架构 (Office instant messaging)"
```

.. or whatever you think is a good translation.

Thanks for being patient as we figure out how to handle multiple languages. 👍

**Comment by yanue** [comment]
hi @zeke , i have changed all into english.

**Pull request merged**
