### PR TITLE
Add Pomolectron

### PR DESCRIPTION
**Pull request by amitmerchant1990**
[Pomolectron](https://github.com/amitmerchant1990/pomolectron) - A Pomodoro app in your menubar/tray.

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the submission, @amitmerchant1990 

I think the app icon would be better as just the tomato, without the 'pomelectron' text beneath it. Can you update the PR to use that?

**Comment by amitmerchant1990** [comment]
@zeke Changed the app icon as suggested. Let me know if you still face any issues.

**Comment by amitmerchant1990** [comment]
Hey @zeke what's the status of the PR?

**Comment by zeke** [comment]
Sorry for the delay. Was out camping. ⛺️

**Comment by amitmerchant1990** [comment]
Thanks @zeke !

**Pull request merged**
