### PR TITLE
add colorpicker

### PR DESCRIPTION
**Pull request by Toinane**
Add my app to the list :)

### CODE REVIEW

**Comment by zeke** [comment]
Nice! Happy to see more design tools being added here.

It looks like the installer DMG has a weird image, and the icon is really low resolution. Can you release a new version that fixes this?

screen shot 2017-02-01 at 11 13 31 am

**Comment by Toinane** [comment]
thank's for your comment!
Yeah, I update the icon now and change installer.

**Comment by Toinane** [comment]
Okay, I updated Colorpicker's icon!
It's now correct :)

**Comment by zeke** [comment]
Hey @Toinane sorry for the delay. I'm still seeing a strange appearance in the new DMG:

screen shot 2017-02-06 at 11 40 46 am

Can you also make the Windows and Mac links two different files, so users don't have to download more than they need?

**Comment by Toinane** [comment]
hey @zeke ! No problem,
for the new DMG, it's normal, the gray background it's for a better look to the icon. But I can remove it later..
And yes, I've changed the download for two different link for windows and mac now!

**Comment by zeke** [comment]
Thanks!

**Comment by Toinane** [comment]
No problem and thanks too!

**Pull request merged**
