### PR TITLE
Submitting Janus Workspace to the electron list of apps

### PR DESCRIPTION
**Pull request by KIvanow**

### CODE REVIEW

**Comment by KIvanow** [comment]
@vanessayuenn it is a private repo. I would be happy to proof that I am using electron for my project. What kind of proof would be most useful for you?

**Comment by vanessayuenn** [comment]
@KIvanow You have a couple options:
- Send a screenshot with the DevTools open
- Send a screenshot of the directory containing the installed app files.
Feel free to also refer to previous PRs for closed source apps such as #455, #419.

**Comment by KIvanow** [comment]
@vanessayuenn Like so?
If it is not what you meant, I apologize and just let me know how can I fix my proof :) 
janusworkspacedistfolder-linuxunpacked
janusworkspacescreenshotwithdevtools

**Comment by KIvanow** [comment]
@vanessayuenn here are better ones :)
janusworkspacefilesscreen
janusworkspaceopenedconsolemoredata

**Comment by vanessayuenn** [comment]
Awesome! Thanks.

**Pull request merged**
