### PR TITLE
Add batcave app

### PR DESCRIPTION
**Pull request by hsbalar**
Experience smooth texting in the dark environment with a classy batcave desktop app electron based on a cool dark theme.

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the submission.

"'A messaging application for user" is not very descriptive. How about something like "A dark-themed chat app"

**Comment by hsbalar** [comment]
Thanks zeke
I have updated app description.

**Comment by zeke** [comment]
`website` is required. Can you change `repository` to `website`?

screen shot 2017-01-13 at 6 14 19 pm

**Comment by hsbalar** [comment]
Updated website in batcave.yml

**Comment by zeke** [comment]
👍

**Pull request merged**
