### PR TITLE
Add Node-RED

### PR DESCRIPTION
**Pull request by zuhito**
I added electron version of Node-RED.

### CODE REVIEW

**Comment by zeke** [comment]
I notice this is a fork of https://github.com/natcl/electron-node-red -- can you explain the relationship between your fork and the source repo?

**Comment by zuhito** [comment]
Thank you for your confirmation. The code in source repository cannot be built and there aren't installer in the source repository. So I completely recreated build code and put installer on my repository. Because the license is Creative Commons Zero v1.0 Universal, there's no problem in terms of license.

**Comment by zeke** [comment]
Happy to merge this, but out of curiosity have you tried upstreaming your changes to the source repository as a pull request?

**Comment by zuhito** [comment]
In general, small changes will be acceptable in the pull request. But in this case, entire build code was newly rewritten. So I didn't have the pull request in the repository.

**Comment by zuhito** [comment]
@zeke Thank you!

**Comment by zeke** [comment]
Thanks for adding it. :)

If you have screenshots, you should consider adding some:

```yml
screenshots:
  -
    imageUrl: 'https://mysite.com/awesome1.png'
    caption: 'Awesome screenshot 1'
    imageLink: 'https://mysite.com/awesome.html'
  -
    imageUrl: 'https://mysite.com/awesome2.png'
    caption: 'Awesome screenshot 2'
    imageLink: 'https://mysite.com/awesome.html'
```

Screenshots are not currently displayed on the site, but they will be soon.

**Pull request merged**
