### PR TITLE
Add "NodeJs Package Manager" app

### PR DESCRIPTION
**Pull request by gurayyarar**
NodeJs Package Manager is organizer of your npm&bower packages

### CODE REVIEW

**Comment by zeke** [comment]
This looks really cool!

Just one suggestion: please change `npm&bower` to `npm & bower` (or `npm and bower`)

You can also add screenshots too, if you're willing. They are not currently displayed on the site, but they will be soon!

```yml
screenshots:
  -
    imageUrl: 'https://mysite.com/awesome1.png'
    caption: 'Awesome screenshot 1'
    imageLink: 'https://mysite.com/awesome.html'
  -
    imageUrl: 'https://mysite.com/awesome2.png'
    caption: 'Awesome screenshot 2'
    imageLink: 'https://mysite.com/awesome.html'
```

**Comment by gurayyarar** [comment]
@zeke thanks for your suggestion. I will make. But i want to ask before. Can we add GIF screenshots to option?

**Comment by zeke** [comment]
> https://github.com/electron/electron.atom.io/commits/gh-pages/_data/processes.yml

As long as they're served over HTTPS 👍

**Comment by gurayyarar** [comment]
@zeke Thanks for your help. 
I edited my app's description and added the screenshots

**Comment by zeke** [comment]
👍

**Pull request merged**
