### PR TITLE
Monerite - A CPU miner for Monero

### PR DESCRIPTION
**Pull request by connorgoggins**
Monerite is a closed-source product that allows users to mine cryptocurrency using their own CPUs. Featuring Monerite (which was built with Electron) on the Electron app store would give users instant access to the service we provide. The DMG is available at https://ufile.io/rh8tq.

Website: www.monerite.com
Screenshots:
screen shot 2018-03-08 at 5 55 40 pm
screen shot 2018-03-08 at 5 54 31 pm

As for proof this was built with electron, here is a screenshot of the app's file hierarchy including the keyword "electron":
screen shot 2018-03-09 at 10 11 48 am
For good measure, here is a screenshot of the result of running "npm start" in the app's directory:
screen shot 2018-03-09 at 10 14 01 am

### CODE REVIEW

**Comment by connorgoggins** [comment]
@ckerr all set! Please let me know if you need anything else.

**Comment by connorgoggins** [comment]
Awesome, thanks! How should I go about adding the DMG/App file to the app
store for download (the application is closed-source)?

**Comment by vanessayuenn** [comment]
Download links for apps are automatically detected only if the assets are on the apps' [Github releases page](https://help.github.com/articles/about-releases/). Currently we don't have support for closed source apps for this.

**Comment by connorgoggins** [comment]
Ok, I made the repository public. Can the download link be published on the
app page now, or is there something else I need to do first?

**Comment by connorgoggins** [comment]
Hi,

Just following up on this. The release has been posted (along with an
updated README in the repository), but these changes don't seem to be
reflected on the Electron App Store.

**Pull request merged**
