### PR TITLE
canSnippet

### PR DESCRIPTION
**Pull request by ademcan**

### CODE REVIEW

**Comment by ademcan** [comment]
Hello, am I supposed to do anything? as the checks have failed...
Thank you for your help.

**Comment by zeke** [comment]
screen shot 2017-06-12 at 9 32 00 am

**Comment by ademcan** [comment]
Thank you very much @zeke

**Comment by zeke** [comment]
Sorry for closing. Hit the wrong button!

Wanna add some keywords to make your app easier for people to find? Some suggestions: 

```yml
keywords:
  - macro
  - code
  - developers
  - editing
  - text
  - productivity
  - keyboard
  - shortcuts
```

**Comment by ademcan** [comment]
Thank you very much for your help and your efforts @zeke, I really appreciated 👍

**Comment by zeke** [comment]
🚀

**Pull request merged**
