### PR TITLE
adding app JumpFM

### PR DESCRIPTION
**Pull request by gkutiel**
A dual panel file manager for Linux. 

jumpfm

See [jumpfm.org](http://jumpfm.org) for more details.

### CODE REVIEW

**Comment by zeke** [comment]
Nice! Do you want to add a screenshot? See https://github.com/electron/electron-apps/blob/master/contributing.md#adding-your-app

**Comment by gkutiel** [comment]
Added.

**Comment by zeke** [comment]
It looks like tests are failing because your YML file has some invalid indentation:

```
/home/travis/build/electron/electron-apps/node_modules/yamljs/lib/Parser.js:312
        throw new ParseException('Indentation problem.', this.getRealCurrentLineNb() + 1, this.currentLine);
        ^
Error: Indentation problem.
```

I think the screenshot props need to be indented.

**Comment by zeke** [comment]
👍

**Pull request merged**
