### PR TITLE
Add VivifyScrum

### PR DESCRIPTION
**Pull request by paxy97**
Vivifyscrum is a Scrum and Kanban tool that allows for easy and intuitive project organization and management.

Website: https://www.vivifyscrum.com/
Repo: https://github.com/Vivify-Ideas/vivifyscrum2-electron/
Screenshots: https://imgur.com/a/gvAxL
Downloads: https://github.com/Vivify-Ideas/vivifyscrum2-electron/releases

### CODE REVIEW

**Comment by paxy97** [comment]
@vanessayuenn What would qualify as evidence? I'm not sure what to do.

**Comment by Toinane** [comment]
@paxy97 You can see this PR #393 who I've asked a proof and the author send me a video that proves his app use Electron.

**Comment by zeke** [comment]
A few ways to show that it's an Electron app:

- Send a screenshot with the DevTools open
- Send a screenshot of the directory containing the installed app files.

**Comment by paxy97** [comment]
@vanessayuenn @Toinane @zeke 
I hope this is enough, since I don't have a Mac and have no idea how to browse the app files.

imgur-2017_12_04-18 04 35
imgur-2017_12_04-18 08 57

If not, I'll get someone with MacOS to take a screenshot

**Comment by vanessayuenn** [comment]
Yup that works @paxy97! Thank you!

**Pull request merged**
