### PR TITLE
✨ Added Playcode to apps list

### PR DESCRIPTION
**Pull request by Meadowcottage**
Adding @playcode to apps list 😄 🎉

### CODE REVIEW

**Comment by zeke** [comment]
This is awesome!

I would say these keywords should be removed: 

- playcode
- desktop-client

And `online-editor` should just be `editor`

**Comment by Meadowcottage** [comment]
Gone ahead and updated the keywords for you.
Should be good to go! 😄

**Comment by zeke** [comment]
You're fast!

**Comment by Meadowcottage** [comment]
Meh. Quick 2 second fix and I'm already at my PC so it's easy 😋

**Pull request merged**
