### PR TITLE
Add reach-podcast-player

### PR DESCRIPTION
**Pull request by SolarFloss**
My app is a podcast player that utilizes RSS feeds in order to allow users to stay up to date with their favorite podcasts.

Repository: https://github.com/SolarFloss/Reach-Podcast-Player

### CODE REVIEW

**Comment by zeke** [comment]
Thanks!

So you know, it's not necessary to keep opening and closing pull requests. You can continue updating an existing PR if you need to make changes. See this guide: https://guides.github.com/introduction/flow/

**Comment by SolarFloss** [comment]
Oh okay. Thank you. I am rather new to all of this. I wasn't exactly sure if I was doing it correctly haha

**Comment by zeke** [comment]
No worries. 👍

**Comment by SolarFloss** [comment]
How long does it generally take for the app to show up on the apps page? Thanks

**Comment by zeke** [comment]
It's usually within a few minutes, but there was a snag in the app release cycle, which I've now fixed: https://github.com/electron/electron-apps/pull/265 -- you should see your app on the site soon.

**Pull request merged**
