### PR TITLE
muno

### PR DESCRIPTION
**Pull request by glenndeb**

### CODE REVIEW

**Comment by zeke** [comment]
Thanks.

I see a typo: Souncloud -> Soundcloud

Can you also remove the name of the app itself from the description?

Otherwise, looks good!

**Comment by glenndeb** [comment]
Fixed the type + name of app in description

**Comment by zeke** [comment]
👌

**Comment by zeke** [comment]
@glenndeb here's a PR to keep descriptions clean in the future: https://github.com/electron/electron-apps/pull/238

**Pull request merged**
