### PR TITLE
Thunder

### PR DESCRIPTION
**Pull request by davidsolorzano20**

### CODE REVIEW

**Comment by zeke** [comment]
It looks like this app's default locale is Spanish. Can you add a `locales` entry to your YML file? For details on how to do that, see https://github.com/electron/electron-apps/blob/master/contributing.md#locales

**Comment by davidsolorzano20** [comment]
@zeke Ready I added the premises.

**Comment by zeke** [comment]
👍

**Comment by jancborchardt** [comment]
Since the app website is down and I could not find any info about it elsewhere, I opened a pull request to disable the entry: https://github.com/electron/apps/pull/694

**Pull request merged**
