### PR TITLE
Add Cards app

### PR DESCRIPTION
**Pull request by rtkhanas**
https://try.cards/
https://contacts.try.cards/

### CODE REVIEW

**Comment by zeke** [comment]
I would recommend a transparent background instead of grey.

**Comment by zeke** [comment]
Bump, @rtkhanas

**Comment by rtkhanas** [comment]
@zeke sorry, for unknown reason I haven't noticed your message. I just pushed a commit with a transparent icon.

**Comment by zeke** [comment]
👌

**Pull request merged**
