### PR TITLE
Add Jukeboks

### PR DESCRIPTION
**Pull request by hirohisa**
Jukeboks is fast viewer / player app, built on Electron.

🙇

### CODE REVIEW

**Comment by zeke** [comment]
Nice! I like the name. I would suggest adding `video` as a tag so more people will be able to find it.

**Comment by hirohisa** [comment]
Thank you for the review , @zeke . I added `video` .

**Comment by zeke** [comment]
🍕

**Comment by hirohisa** [comment]
🍣

**Comment by zeke** [comment]
lol

**Pull request merged**
