### PR TITLE
add github-browser

### PR DESCRIPTION
**Pull request by tborychowski**

### CODE REVIEW

**Comment by zeke** [comment]
Our legal team has advised us to disallow apps that are using the names of other companies or icons that we find too similar to the logos of other companies without verifying their permission to do so. We would still be happy to feature your app. If you are an author of this app and would like to see it on the site, please change the icon and update this PR to use the new icon.

Apologies for the inconvenience, and thanks for your understanding.

cc @lee-dohm

**Comment by lee-dohm** [comment]
For future reference, with regard to GitHub's logos see the [GitHub logo guidelines](https://github.com/logos). As for the name of the app, it shouldn't start with the word "GitHub". In general, you may refer to GitHub in a relational phrase to say that the project is "compatible with", "on", or "for" GitHub, or something along those lines.

**Comment by tborychowski** [comment]
understood, thanks!

**Comment by zeke** [comment]
@tborychowski please do submit another PR if you get around to making those changes.

**Pull request closed without merging**
