### PR TITLE
adminScheduler

### PR DESCRIPTION
**Pull request by danieltoorani**
Scheduling for client/admin relationships

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the PR!

It's not necessary to mention Electron in the description. I would recommend something like "Scheduling for client/admin relationships"

**Comment by danieltoorani** [comment]
So Ive updated the description is there anything else I need to do?

**Comment by zeke** [comment]
👍

**Comment by danieltoorani** [comment]
Thank you!

**Pull request merged**
