### PR TITLE
Add Papyrus

### PR DESCRIPTION
**Pull request by morkro**

### CODE REVIEW

**Comment by zeke** [comment]
Thank you very much for your submission for inclusion in the Electron app list. We're uncomfortable with including your application in the list because of the icon's similarity to the [Dropbox logo](https://www.dropbox.com/branding). Because of this, we've decided to not include your application in our list.

If you're willing to change your application icon, please open a new pull request and we will happily include your app.

Thanks very much for your submission and your use of Electron!

**Comment by morkro** [comment]
Thanks for the info, I will change the logo :)
How does that work with [Caprine](http://electron.atom.io/apps/?q=caprine) then? It's also using the official Facebook Messenger icon and is not an official client.

**Comment by zeke** [comment]
I was unaware that Caprine's logo is using the FB messenger icon.

Thoughts, @sindresorhus? Maybe change the icon to a goat?

🐐

**Comment by zeke** [comment]
Merging and setting `disabled: true`, in case @morkro wants to update the icon at some point.

**Pull request merged**
