### PR TITLE
add smallpdf

### PR DESCRIPTION
**Pull request by alexd765**
[website](https://smallpdf.com/desktop)
[screenshot](https://download.smallpdf.com/assets/smallpdf-desktop-screenshot.png)

### CODE REVIEW

**Comment by alexd765** [comment]
smallpdf-proof

**Comment by alexd765** [comment]
I am confused about the octocat comment. The smallpdf logo is completely
smallpdf-logo-electron
 different.

**Comment by ckerr** [comment]
Yes, the icon question came up because I'm an idiot -- while I was looking at the diff in my browser, your icon failed to load and instead I got an octocat error. Sorry for the noise. :man_facepalming:

**Comment by alexd765** [comment]
No problem.
Thanks for the quick merge.

**Pull request merged**
