### PR TITLE
add writebar

### PR DESCRIPTION
**Pull request by alexander-shvets**
[https://writebar.js.org]()    

screenshot

### CODE REVIEW

**Comment by alexander-shvets** [comment]
Thank you ) When I can see it on the [website](https://electronjs.org/apps/writebar)  ?

**Comment by zeke** [comment]
Hey @alexander-shvets there's a failing test in the publish script for this module. I'll have to fix that before your app will land on the site. I'll keep you posted.

**Comment by zeke** [comment]
See https://github.com/electron/electron-apps/issues/504 -- once a fix for that lands, your app should be live shortly thereafter.

**Comment by zeke** [comment]
Your app is live on the site now. Sorry for the delay! https://electronjs.org/apps

**Pull request merged**
