### PR TITLE
Added Pomotroid app

### PR DESCRIPTION
**Pull request by Splode**
Added **Pomotroid**, a simple, configurable, and visually-pleasing Pomodoro timer. Builds for Windows and Mac OS.
[Pomotroid Repo on Github](https://github.com/Splode/pomotroid)

### CODE REVIEW

**Comment by codebytere** [comment]
@Splode looks like you accidentally committed the `package-lock`, revert that and we can get this merged!

**Comment by Splode** [comment]
Sorry about that.

I've reverted that commit and re-commited without `package-lock.json`. Shall I remake the pull request? (I'm new to the open source contribution workflow)

**Comment by codebytere** [comment]
you have 9 files marked with changes now...i'd just copy the two you need out, roll back all your changes, and the force push a single commit with just the two files you need (yaml and image)

**Comment by Splode** [comment]
Ok, phew. I believe that worked. Thank you for walking me through that 👍

**Pull request merged**
