### PR TITLE
Add Lectrote

### PR DESCRIPTION
**Pull request by dylan-k**
Lectrote
https://github.com/erkyrath/lectrote

The Interactive Fiction (IF) interpreter in an Electron shell

Version 1.2.5
Created by Andrew Plotkin erkyrath@eblong.com
Download the latest Lectrote app
Lectrote packages up IF interpreters with the Chromium browser as a Mac/Win/Linux app.

When launched, it prompts you to select a game file to play. You can play several games at the same time in separate windows. Your position is always autosaved; when you launch a game, your last play session will automatically be resumed.

Lectrote currently supports:

Glulx games (.ulx or .gblorb), as produced by Inform 7.
Z-code games (.z3/.z4/.z5/.z8 or .zblorb), as produced by Inform 7 or earlier versions of Inform.
Hugo games (.hex).
Ink compiled game files (.json), as produced by the Ink scripting language.
You can also use this package to construct a "bound game" -- an app which plays a single built-in game. This is a package containing Chromium, the interpreter, your game file, and perhaps some additional configuration. You can distribute this as a standalone game application; it's bulky but it lets people play your game.

### CODE REVIEW

**Comment by ckerr** [comment]
@dylan-k bump

**Comment by dylan-k** [comment]
Their icon is here, does this help?

lectrote

**Comment by vanessayuenn** [comment]
@dylan-k your icon is 128px x 128px

**Comment by zeke** [comment]
> your icon is 128px x 128px

That's actually a valid size. The docs were incorrect. I opened https://github.com/electron/electron-apps/pull/591 to update the docs.

**Pull request merged**
