### PR TITLE
added autoEdit app to list of electron apps

### PR DESCRIPTION
**Pull request by pietrop**
added [autoEdit.io](http://autoedit.io) app to the list of electron apps.

I think it be a great show case for the electron community of an example of text based video editing that makes video production faster, easier, and more accessible.

### CODE REVIEW

**Comment by zeke** [comment]
That icon is going to look small because it has so much empty space around it. I would suggest scaling it up to fit the bounding box.

Also it looks like the tests are failing.

> human-submitted app data autoedit icon exists as autoedit-icon.png:
> autoedit-icon.png not found

**Comment by pietrop** [comment]
Thanks, ok I've modified the image name and size, let me know if this is good to go or if there's anything else I can do.

**Comment by zeke** [comment]
Sorry, the icon has to be square and between 256px and 1024px in dimension.

**Comment by pietrop** [comment]
Sorry, for the back and forth, is this better?
It is now the same size as the one for `atom` in that folder.

**Comment by zeke** [comment]
👍

**Comment by pietrop** [comment]
awesome thanks!

**Comment by pietrop** [comment]
I don't see it in the main site under [https://electron.atom.io/apps/?q=video](https://electron.atom.io/apps/?q=video) , is there anything else I need to do?

**Comment by zeke** [comment]
@pietrop it looks like there is a hiccup in our deployment. I'll let you know when it's live.

**Comment by zeke** [comment]
@pietrop your app is now on the site!

FYI, here's the little bug that was blocking it: https://github.com/electron/electron-apps/pull/193

**Comment by pietrop** [comment]
Awesome @zeke ! thanks!

**Pull request merged**
