### PR TITLE
Add SparkChess

### PR DESCRIPTION
**Pull request by armandn**
SparkChess is a chess game with single-player and multiplayer capabilities.
It's free for online play and available as a paid version with extra features as an Electron app.

Website: https://www.sparkchess.com
Screenshot: http://www.sparkchess.com/res/img/promo/chess-electron.jpg

Thank you.

### CODE REVIEW

**Comment by armandn** [comment]
Hi Vanessa, what constitutes evidence of the app being built with Electron?
I'm adding 2 screenshots (win/mac) from the folder structure.
I can send you the app if you want.
mac
win

**Comment by vanessayuenn** [comment]
@armandn you can refer to #393 where the author did a simple screencast of their app.

**Comment by armandn** [comment]
@vanessayuenn, here's a screencast showing the build process (with electron-packager) as well as a bit of the app's functionality: http://www.sparkchess.com/electron-build-win.mp4

Thanks!

**Comment by vanessayuenn** [comment]
Awesome! Thank you. :)

**Pull request merged**
