### PR TITLE
new url for cards (old one expired)

### PR DESCRIPTION
**Pull request by noformnocontent**

### CODE REVIEW

**Comment by codebytere** [comment]
@noformnocontent please fix conflicts before this can be merged

**Comment by noformnocontent** [comment]
what conflicts?

**Comment by zeke** [comment]
`apps/cards/cards.yml`

**Comment by noformnocontent** [comment]
oh, turns out, there was [another PR from 3 weeks ago](https://github.com/electron/electron-apps/commit/2443e44e5abd2e96e190bb5b11292e565e066cbc#diff-07483f5fbfd1fef0aa7a17ef1ce56e87) which fixed it all

**Pull request closed without merging**
